USE acme_commercial_property;


INSERT INTO Manufacturer (Name) VALUES
    ('Aaon'),
    ('AAON'),
    ('Armstrong'),
    ('Armstrong'),
    ('Grundfos'),
    ('Grundfos'),
    ('Armstrong'),
    ('Armstrong'),
    ('Bell & Gossett'),
    ('Bell & Gossett'),
    ('Bell & Gossett'),
    ('Bell & Gossett'),
    ('Bell & Gossett'),
    ('Bell & Gossett'),
    ('Condair'),
    ('Cummins'),
    ('Daikin'),
    ('Greenheck'),
    ('Greenheck'),
    ('Greenheck'),
    ('Greenheck'),
    ('Greenheck'),
    ('Greenheck'),
    ('Greenheck'),
    ('CaptiveAire'),
    ('CaptiveAire'),
    ('Grundfos'),
    ('Grundfos'),
    ('Huntair'),
    ('Huntair'),
    ('IAC'),
    ('IAC'),
    ('IAC'),
    ('Lochinvar'),
    ('Lochinvar'),
    ('MITSUBISHI'),
    ('Mitsubishi'),
    ('MITSUBISHI'),
    ('Mitsubishi'),
    ('MITSUBISHI'),
    ('Mitsubishi'),
    ('MITSUBISHI'),
    ('Mitsubishi'),
    ('MITSUBISHI'),
    ('Mitsubishi'),
    ('POWER QUALITY INTERNATIONAL'),
    ('POWER QUALITY INTERNATIONAL'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Quincy'),
    ('Southern Tier Technologies'),
    ('Southern Tier Technologies'),
    ('Eaton'),
    ('Siemens'),
    ('GE'),
    ('Siemens'),
    ('GE'),
    ('Eaton'),
    ('Eaton'),
    ('King Electric'),
    ('King Electric'),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    ('Nordyne'),
    ('Armstrong Air'),
    ('Goodman / Amana'),
    ('Eaton'),
    ('Midea'),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL);
;

