USE acme_commercial_property;

## Manufacturer Population

INSERT INTO Manufacturer (Name) VALUES
    ('Aaon'),
    ('AAON'),
    ('Armstrong'),
    ('Armstrong'),
    ('Grundfos'),
    ('Grundfos'),
    ('Armstrong'),
    ('Armstrong'),
    ('Bell & Gossett'),
    ('Bell & Gossett'),
    ('Bell & Gossett'),
    ('Bell & Gossett'),
    ('Bell & Gossett'),
    ('Bell & Gossett'),
    ('Condair'),
    ('Cummins'),
    ('Daikin'),
    ('Greenheck'),
    ('Greenheck'),
    ('Greenheck'),
    ('Greenheck'),
    ('Greenheck'),
    ('Greenheck'),
    ('Greenheck'),
    ('CaptiveAire'),
    ('CaptiveAire'),
    ('Grundfos'),
    ('Grundfos'),
    ('Huntair'),
    ('Huntair'),
    ('IAC'),
    ('IAC'),
    ('IAC'),
    ('Lochinvar'),
    ('Lochinvar'),
    ('MITSUBISHI'),
    ('Mitsubishi'),
    ('MITSUBISHI'),
    ('Mitsubishi'),
    ('MITSUBISHI'),
    ('Mitsubishi'),
    ('MITSUBISHI'),
    ('Mitsubishi'),
    ('MITSUBISHI'),
    ('Mitsubishi'),
    ('POWER QUALITY INTERNATIONAL'),
    ('POWER QUALITY INTERNATIONAL'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Price'),
    ('PRICE'),
    ('Quincy'),
    ('Southern Tier Technologies'),
    ('Southern Tier Technologies'),
    ('Eaton'),
    ('Siemens'),
    ('GE'),
    ('Siemens'),
    ('GE'),
    ('Eaton'),
    ('Eaton'),
    ('King Electric'),
    ('King Electric'),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    ('Nordyne'),
    ('Armstrong Air'),
    ('Goodman / Amana'),
    ('Eaton'),
    ('Midea'),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL),
    (NULL);
;

## CategoryID population ##
INSERT INTO Category (Name)
VALUES
    ('Packaged Rooftop Unit'),
    ('Air Separator'),
    ('Hydronic Circulation Pump'),
    ('Expansion Vessel'),
    ('Steam Humidifier'),
    ('Standby Generator'),
    ('Air-Cooled Chiller'),
    ('Extract Fan'),
    ('Air Handling Unit'),
    ('Duct Silencer'),
    ('Gas-Fired Boiler'),
    ('Split Air-Conditioning System'),
    ('Dry-Type Transformer'),
    ('Variable Air Volume Terminal'),
    ('Rotary Screw Air Compressor'),
    ('Surge Protective Device'),
    ('Electrical Panelboard'),
    ('Electrical Disconnect Switch'),
    ('Electric Unit Heater'),
    ('Automatic Transfer Switch'),
    ('Packaged Heat Pump'),
    ('Furnace'),
    ('Air Handler'),
    ('Main Switchboard'),
    ('Electrical Distribution Unit'),
    ('Heating Module'),
    ('Lighting Module'),
    ('Lighting Panel'),
    ('Other HVAC Equipment'),
    ('Other Electrical Distribution Equipment');

## Product Table Population ##
INSERT INTO Product (Name, CategoryID, ManufacturerID, ModelNum)
VALUES
    ('Packaged Rooftop Unit:Aaon:RQ-003', 1, 1, 'RQ-003'),
    ('Packaged Rooftop Unit:AAON:RQ-003', 1, 2, 'RQ-003'),
    ('Air Separator:Armstrong:VAS-6U', 2, 3, 'VAS-6U'),
    ('Air Separator:Armstrong:VAS-2', 2, 4, 'VAS-2'),
    ('Hydronic Circulation Pump:Grundfos:TP 40LP5/5.2', 3, 5, 'TP 40LP5/5.2'),
    ('Hydronic Circulation Pump:Grundfos:TP 40LP5/5.2', 3, 6, 'TP 40LP5/5.2'),
    ('Expansion Vessel:Armstrong:50-L', 4, 7, '50-L'),
    ('Expansion Vessel:Armstrong:50-L', 4, 8, '50-L'),
    ('Hydronic Circulation Pump:Bell & Gossett:XL 65‑130', 3, 9, 'XL 65‑130'),
    ('Hydronic Circulation Pump:Bell & Gossett:XL 65‑130', 3, 10, 'XL 65‑130'),
    ('Hydronic Circulation Pump:Bell & Gossett:TP 40LP5/5.2', 3, 11, 'TP 40LP5/5.2'),
    ('Hydronic Circulation Pump:Bell & Gossett:TP 40LP5/5.2', 3, 12, 'TP 40LP5/5.2'),
    ('Hydronic Circulation Pump:Bell & Gossett:TP 40LP5/5.2', 3, 13, 'TP 40LP5/5.2'),
    ('Hydronic Circulation Pump:Bell & Gossett:TP 40LP5/5.2', 3, 14, 'TP 40LP5/5.2'),
    ('Steam Humidifier:Condair:RS 180', 5, 15, 'RS 180'),
    ('Standby Generator:Cummins', 6, 16, NULL),
    ('Air-Cooled Chiller:Daikin:R32‑10T', 7, 17, 'R32‑10T'),
    ('Extract Fan:Greenheck:SP-A390-VG', 8, 18, 'SP-A390-VG'),
    ('Extract Fan:Greenheck:SP-B200', 8, 19, 'SP-B200'),
    ('Extract Fan:Greenheck:SP-B200', 8, 20, 'SP-B200'),
    ('Extract Fan:Greenheck:SP-B200', 8, 21, 'SP-B200'),
    ('Extract Fan:Greenheck:SP-B200', 8, 22, 'SP-B200'),
    ('Extract Fan:Greenheck:SP-B200', 8, 23, 'SP-B200'),
    ('Extract Fan:Greenheck:SQ-140-VG', 8, 24, 'SQ-140-VG'),
    ('Extract Fan:CaptiveAire:DU50HFA / DU85HFA', 8, 25, 'DU50HFA / DU85HFA'),
    ('Extract Fan:CaptiveAire:DU50HFA / DU85HFA', 8, 26, 'DU50HFA / DU85HFA'),
    ('Hydronic Circulation Pump:Grundfos:TP 40LP5/5.2', 3, 27, 'TP 40LP5/5.2'),
    ('Hydronic Circulation Pump:Grundfos:TP 40LP5/5.2', 3, 28, 'TP 40LP5/5.2'),
    ('Air Handling Unit:Huntair:CSU', 9, 29, 'CSU'),
    ('Air Handling Unit:Huntair:CSU', 9, 30, 'CSU'),
    ('Duct Silencer:IAC:3LFL 44X24', 10, 31, '3LFL 44X24'),
    ('Duct Silencer:IAC:3LFL 48X24', 10, 32, '3LFL 48X24'),
    ('Duct Silencer:IAC:3LFL 48X24', 10, 33, '3LFL 48X24'),
    ('Gas-Fired Boiler:Lochinvar:KHB285N', 11, 34, 'KHB285N'),
    ('Gas-Fired Boiler:Lochinvar:KHB285N', 11, 35, 'KHB285N'),
    ('Split Air-Conditioning System:MITSUBISHI:IDU: PKA-AL18NL (R-454B)                                                  ODU: PUZ-AK18NL', 12, 36, 'IDU: PKA-AL18NL (R-454B)                                                  ODU: PUZ-AK18NL'),
    ('Split Air-Conditioning System:Mitsubishi:IDU: PKA-AL18NL / ODU: PUZ-AK18NL', 12, 37, 'IDU: PKA-AL18NL / ODU: PUZ-AK18NL'),
    ('Split Air-Conditioning System:MITSUBISHI:IDU: PKA-AL18NL (R-454B)                                                  ODU: PUZ-AK18NL', 12, 38, 'IDU: PKA-AL18NL (R-454B)                                                  ODU: PUZ-AK18NL'),
    ('Split Air-Conditioning System:Mitsubishi:IDU: PKA-AL18NL / ODU: PUZ-AK18NL', 12, 39, 'IDU: PKA-AL18NL / ODU: PUZ-AK18NL'),
    ('Split Air-Conditioning System:MITSUBISHI:IDU: PKA-AL18NL (R-454B)                                                  ODU: PUZ-AK18NL', 12, 40, 'IDU: PKA-AL18NL (R-454B)                                                  ODU: PUZ-AK18NL'),
    ('Split Air-Conditioning System:Mitsubishi:IDU: PKA-AL18NL / ODU: PUZ-AK18NL', 12, 41, 'IDU: PKA-AL18NL / ODU: PUZ-AK18NL'),
    ('Split Air-Conditioning System:MITSUBISHI:IDU: PKA-AL18NL (R-454B)                                                  ODU: PUZ-AK18NL', 12, 42, 'IDU: PKA-AL18NL (R-454B)                                                  ODU: PUZ-AK18NL'),
    ('Split Air-Conditioning System:Mitsubishi:IDU: PKA-AL18NL / ODU: PUZ-AK18NL', 12, 43, 'IDU: PKA-AL18NL / ODU: PUZ-AK18NL'),
    ('Split Air-Conditioning System:MITSUBISHI:IDU: PKA-AL18NL (R-454B)                                                  ODU: PUZ-AK18NL', 12, 44, 'IDU: PKA-AL18NL (R-454B)                                                  ODU: PUZ-AK18NL'),
    ('Split Air-Conditioning System:Mitsubishi:IDU: PKA-AL18NL / ODU: PUZ-AK18NL', 12, 45, 'IDU: PKA-AL18NL / ODU: PUZ-AK18NL'),
    ('Dry-Type Transformer:POWER QUALITY INTERNATIONAL:DV30-60-045-480:208/120-150-AL-ZS', 13, 46, 'DV30-60-045-480:208/120-150-AL-ZS'),
    ('Dry-Type Transformer:POWER QUALITY INTERNATIONAL:DV30-60-030-480:208/120-150-AL-ZS', 13, 47, 'DV30-60-030-480:208/120-150-AL-ZS'),
    ('Variable Air Volume Terminal:Price:SDV5', 14, 48, 'SDV5'),
    ('Variable Air Volume Terminal:PRICE:SDV5', 14, 49, 'SDV5'),
    ('Variable Air Volume Terminal:Price:SDV5', 14, 50, 'SDV5'),
    ('Variable Air Volume Terminal:PRICE:SDV5', 14, 51, 'SDV5'),
    ('Variable Air Volume Terminal:Price:SDV5', 14, 52, 'SDV5'),
    ('Variable Air Volume Terminal:PRICE:SDV5', 14, 53, 'SDV5'),
    ('Variable Air Volume Terminal:Price:SDV5', 14, 54, 'SDV5'),
    ('Variable Air Volume Terminal:PRICE:SDV5', 14, 55, 'SDV5'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 56, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 57, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 58, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 59, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 60, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 61, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 62, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 63, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 64, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 65, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 66, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV', 14, 67, 'SDV'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 68, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV', 14, 69, 'SDV'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 70, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 71, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 72, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 73, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 74, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 75, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 76, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 77, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 78, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 79, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 80, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 81, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 82, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV', 14, 83, 'SDV'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 84, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 85, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 86, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 87, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 88, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 89, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 90, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 91, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 92, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 93, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 94, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 95, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 96, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 97, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 98, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 99, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 100, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 101, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 102, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 103, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 104, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 105, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 106, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 107, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 108, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 109, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 110, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 111, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 112, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 113, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 114, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 115, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 116, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 117, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 118, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 119, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 120, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 121, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 122, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV-2-1', 14, 123, 'SDV-2-1'),
    ('Variable Air Volume Terminal:Price:SDV', 14, 124, 'SDV'),
    ('Variable Air Volume Terminal:PRICE:SDV', 14, 125, 'SDV'),
    ('Rotary Screw Air Compressor:Quincy:V310', 15, 126, 'V310'),
    ('Surge Protective Device:Southern Tier Technologies:T45120Y100AWAJ2S', 16, 127, 'T45120Y100AWAJ2S'),
    ('Surge Protective Device:Southern Tier Technologies:T45277Y100AWAJ2S', 16, 128, 'T45277Y100AWAJ2S'),
    ('Electrical Panelboard:Eaton:PRL‑2A', 17, 129, 'PRL‑2A'),
    ('Electrical Panelboard:Siemens:P1E42MC250CT', 17, 130, 'P1E42MC250CT'),
    ('Electrical Panelboard:GE:AQU3422RCXAXT1B4', 17, 131, 'AQU3422RCXAXT1B4'),
    ('Electrical Panelboard:Siemens:P1E42MC250CT', 17, 132, 'P1E42MC250CT'),
    ('Electrical Panelboard:GE:AQU3422RCXAXT1B4', 17, 133, 'AQU3422RCXAXT1B4'),
    ('Electrical Panelboard:Eaton:PRL‑2A', 17, 134, 'PRL‑2A'),
    ('Electrical Disconnect Switch:Eaton:NF290050866637000356', 18, 135, 'NF290050866637000356'),
    ('Electric Unit Heater:King Electric:PKB‑5‑1‑TB', 19, 136, 'PKB‑5‑1‑TB'),
    ('Electric Unit Heater:King Electric:PKB‑5‑1‑TB', 19, 137, 'PKB‑5‑1‑TB'),
    ('Heating Module:Generic', 26, 138, NULL),
    ('Lighting Module:Generic', 27, 139, NULL),
    ('Lighting Panel:Generic', 28, 140, NULL),
    ('Automatic Transfer Switch:Generic', 20, 141, 'BTPCC*2410738'),
    ('Automatic Transfer Switch:Generic', 20, 142, 'BTPCC*2490737'),
    ('Packaged Heat Pump:Generic', 21, 143, NULL),
    ('Packaged Heat Pump:Nordyne:921484', 21, 144, '921484'),
    ('Furnace:Armstrong Air:41W51', 22, 145, '41W51'),
    ('Air Handler:Goodman / Amana:B13400312S', 23, 146, 'B13400312S'),
    ('Electrical Distribution Unit:Eaton:PRL2A‑225A', 25, 147, 'PRL2A‑225A'),
    ('Lighting Module:Midea:11002015006201', 27, 148, '11002015006201'),
    ('Lighting Panel:Generic', 28, 149, 'NQ290050866637000440'),
    ('Lighting Panel:Generic', 28, 150, 'NQ290050866637000380'),
    ('Main Switchboard:Generic', 24, 151, 'M07886133 / M07256161'),
    ('Surge Protective Device:Generic', 16, 152, 'T45277Y125ALAM1C'),
    ('Dry-Type Transformer:Generic', 13, 153, NULL),
    ('Dry-Type Transformer:Generic', 13, 154, NULL),
    ('Dry-Type Transformer:Generic', 13, 155, 'PHA9586703'),
    ('Dry-Type Transformer:Generic', 13, 156, 'DV30-60-030-480:208/120-150-AL-ZS'),
    ('Dry-Type Transformer:Generic', 13, 157, 'DV30-60-015-480:208/120-150-AL-ZS'),
    ('Dry-Type Transformer:Generic', 13, 158, NULL);